sudo: required

language: node_js

addons:
  chrome: stable

env:
  global:
  - ENCRYPTION_LABEL: "56bfe4a947b1"
  - COMMIT_AUTHOR_EMAIL: "sebastian.fuss@googlemail.com"

node_js:
  - "11"

before_install:

install:
  # Install the deps
  - npm install
  # Run lint
  - ng lint
  # Build the libs
  - npm run build:lib
  # Prepare webdriver manager (chrome only)
  - ./node_modules/protractor/bin/webdriver-manager update --gecko=false

script:
  # Execute the tests
  - ng e2e

after_success:
  - export DEMO_DIST=$(pwd)/dist
  - echo $DEMO_DIST
  # Build the demo app
  - ng build --prod --baseHref=/ngx-page-scroll
  - ./deploy.sh

