language: node_js
node_js:
  - "12.18.3"
sudo: true

addons:
  chrome: beta

before_script:
  - npm install -g @angular/cli
  # Install commitlint cli for travis
  - npm install @commitlint/travis-cli

script:
  # Lint the commit messages
  - commitlint-travis
  - ng lint
  - npm run build:lib
  - ng test --watch false --browsers ChromeHeadless
  - ng e2e --protractor-config='e2e/protractor.ci.conf.js'
  - npm run build:app

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  local_dir: dist/ngx-page-scroll-demo
  keep-history: true
  name:
  on:
    branch: master
